name: Deploy Admin Console

on:
  push:
    branches:
      - main
    paths:
      - 'admin-console/**'
defaults:
  run:
    working-directory: admin-console

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Configure Amplify
        uses: ambientlight/amplify-cli-action@0.3.0
        with:
          amplify_command: configure
          amplify_env: dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2

      - name: Install NPM packages
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Deploy to Amplify
        uses: ambientlight/amplify-cli-action@0.3.0
        with:
          amplify_command: publish
          amplify_env: dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
